global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'app_http'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'app_metrics'
    static_configs:
      - targets: ['app:8001']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

